#server
server:
  port: 8889
  servlet:
    application-display-name: cm_blog

#datasource
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog #?useUnicode=true&characterEncoding=UTF-8&serverTimeZone=UTC
    username: root
    password: 403630
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  main:
    banner-mode: off

#mybatis-plus:
mybatis-plus:
  global-config:
    banner: off
    db-config:
      table-prefix: ms_  # 数据库表名前缀
